### ISSUE TITLE
CLI source gone?

### ISSUE THREAD

**Issue by mindreframer** [sequinstream/sequin#146]
Great project, I watch it with quite curiosity. Fan of anything using Postgres Logical replication in some interesting and creative  ways. I might try sequin as a light-weight Kafka alternative in a side project in future, right now there seems to be quite some churn :) 

I have just noticed, that when you commited https://github.com/sequinstream/sequin/commit/f2f05a2d9c6299545bfd03b87a6df0c280f69e88 (Flatten project), the CLI folder was removed and now seems to be in a private repo. Any plans to make it open-source again? 

Cheers, 
Roman

**Comment by acco** [comment]
Hey @mindreframer, apologies that we missed this!

The CLI was proving too confusing for learning the Sequin basics and getting up and running. So we reverted to web UI first. However, we plan to reintroduce the CLI later this month. It will be more basic and allow for basic CRUD of things like databases and consumers over our API.

This week we'll finish our big refactor and include in the README steps to get up and running with Sequin locally. Alternatively, you can play around with Sequin [here](https://console.sequinstream.com/).

We'll post a release/update when the CLI makes its way back into the project.
