### ISSUE TITLE
BUG: backfill oban worker fails on current main branch

### ISSUE THREAD

**Issue by mindreframer** [sequinstream/sequin#147]
this line causes issues: 
```elixir
# in Sequin.Replication.BackfillPostgresTableWorker
messages = create_messages(postgres_database.name, schema, table, columns, rows, postgres_replication.key_format)
```

Error message: 
```bash
"{\"at\": \"2024-08-25T21:43:25.075292Z\", \"error\": \"** (KeyError) key :key_format not found in: %Sequin.Replication.PostgresReplicationSlot{\\n  __meta__: #Ecto.Schema.Metadata<:loaded, \\\"sequin_config\\\", \\\"postgres_replication_slots\\\">,\\n  id: \\\"adf0dc44-21c2-41d1-9231-ec5297b92509\\\",\\n  publication_name: 
```

Replication struct: 

```
postgres_replication: %Sequin.Replication.PostgresReplicationSlot{
  __meta__: #Ecto.Schema.Metadata<:loaded, "sequin_config", "postgres_replication_slots">,
  id: "adf0dc44-21c2-41d1-9231-ec5297b92509",
  publication_name: "sequin_pub",
  slot_name: "sequin_slot",
  account_id: "58762921-f7f2-435d-a4ad-ab0ffd4db77e",
  account: #Ecto.Association.NotLoaded<association :account is not loaded>,
  postgres_database_id: "0e80d13f-862a-4c22-9016-9154329bde7c",
  postgres_database: #Ecto.Association.NotLoaded<association :postgres_database is not loaded>,
  http_pull_consumers: #Ecto.Association.NotLoaded<association :http_pull_consumers is not loaded>,
  http_push_consumers: #Ecto.Association.NotLoaded<association :http_push_consumers is not loaded>,
  info: nil,
  inserted_at: ~U[2024-08-25 21:43:25Z],
  updated_at: ~U[2024-08-25 21:43:25Z]
}
```

**Comment by acco** [comment]
Hey @mindreframer , nice catch!

We have two stream types (still settling on terms): the WAL stream (fka change stream) and Table stream (fka sync stream). We've been focused on getting the WAL stream stable (finished last week) and will now be working on the table stream. The table stream is best for turning a table into something that behaves like a Kafka topic, which is what you seek.

We'll update here as we stabilize the table stream and get backfills and replays working -- should be within next week or two.

**Comment by mindreframer** [comment]
@acco Thanks for the response! 

I have noticed, that there were quite a lot of significant changes in the recent weeks on Sequinstream, so I figured that you are adjusting the original ideas and concepts. 

I'll re-check things, when the dust has settled 😄, maybe then it will be a bit more stable. Quite excited about this project! 

BTW, just found this article: 
- https://shortishly.com/blog/cache-consistency-with-streaming-replication
- https://github.com/shortishly/pgec

Maybe some implementation details about backfilling in combination with gen_statem might be of interest to you. 


Cheers and thanks also for your work on the [Sync](https://github.com/josevalim/sync/tree/main) project, that is quite a surprising turn of events. Maybe we'll have a built-in sync engine for Phoenix in some distant bright future 🙂

**Comment by acco** [comment]
@mindreframer Sounds good, I'll post a comment here when the dust has settled!

Very cool articles, PGEC looks great – thanks for putting on my radar! Indeed, the backfilling strategy there is probably very relevant to us, will check it out!

Was neat to collaborate on some Postgres tricks for the sync project :)

**Comment by mindreframer** [comment]
Hey, found another one with some gen_statem tricks 
- https://erlangforums.com/t/pgmp-postgresql-client-with-logical-replication-to-ets/1707/16

This forum thread also contains some interesting details about using "binary" mode for the initial table snapshot, with some numbers
>>  With a local PostgreSQL a snapshot of ~112k rows currently takes roughly 4 seconds into ETS - that is batching 5k rows (another feature of extended query)

Not sure, if this is of any use to you right now, but this might be good for later performance optimization.

**Comment by acco** [comment]
@mindreframer What a great thread, thanks for linking it! 🙏

**Comment by acco** [comment]
@mindreframer We've made substantial progress here. You can now create a Row Consumer, indicate the sort column we ought to use (eg `updated_at`), and indicate where in the table you want the consumer to start.

Coming up soon is the ability to rewind the cursor to wherever you like as well as replay certain sections of a table.

Definitely worth checking out, and you can try things out in our cloud: https://console.sequinstream.com

Let me know what you think and if you have any questions!
