### ISSUE TITLE
FR: Kotlin Multiplatform SDK support.

### ISSUE THREAD

**Issue by Shabinder** [sequinstream/sequin#211]
Hi team, Congrats on the launch, and it looks interesting, will be diving more in depth soon.

Opening this to request a kotlin multiplatform sdk, since I noticed there was no sdk in kotlin.

**Comment by acco** [comment]
Hey @Shabinder – thanks for the request! I'm not familiar with the Kotlin ecosystem - mind suggesting a couple of Kotlin SDKs that are good gold standards for us to pattern off of?

**Comment by Shabinder** [comment]
A few from top of my head, should be good for references.

https://github.com/supabase-community/supabase-kt
https://github.com/getsentry/sentry-kotlin-multiplatform
https://github.com/cashapp/zipline
https://github.com/arkivanov/Essenty

**Comment by acco** [comment]
Thanks @Shabinder! We'll have a Kotlin SDK soon, I'll let you know when we have an ETA

**Comment by acco** [comment]
Hey @Shabinder --

We've decided to hold on expanding SDKs for now. The API for pulling messages is pretty simple! There's only three endpoints (receive/ack/nack). Below is an LLM translation of the curl commands in our docs to requests using OkHttp.

When we have comprehensive APIs for managing resources (adding/removing consumers), SDKs will become more relevant for us again. But we're going to start with config files first (most preferred) before focusing too much on the HTTP management interface.

Make sense? If there end up being specific things you need for Kotlin, don't hesitate to let me know.

```kotlin
import okhttp3.*
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.toRequestBody

val client = OkHttpClient()
val JSON = "application/json; charset=utf-8".toMediaType()
val API_TOKEN = "YOUR_API_TOKEN"

// Receive request
fun receiveRequest() {
    val requestBody = """
        { "batch_size": 10 }
    """.trimIndent().toRequestBody(JSON)

    val request = Request.Builder()
        .url("https://api.sequinstream.com/api/http_pull_consumers/orders-pull-consumer/receive")
        .header("Authorization", "Bearer $API_TOKEN")
        .post(requestBody)
        .build()

    client.newCall(request).execute().use { response ->
        if (!response.isSuccessful) throw IOException("Unexpected code $response")
        println(response.body?.string())
    }
}

// Ack request
fun ackRequest() {
    val requestBody = """
        {
            "ack_tokens": ["MTYyeJ7abUjl1pO", "MTYyeJ7abUjl1pP"]
        }
    """.trimIndent().toRequestBody(JSON)

    val request = Request.Builder()
        .url("https://api.sequinstream.com/api/http_pull_consumers/orders-pull-consumer/ack")
        .header("Authorization", "Bearer $API_TOKEN")
        .post(requestBody)
        .build()

    client.newCall(request).execute().use { response ->
        if (!response.isSuccessful) throw IOException("Unexpected code $response")
        println(response.body?.string())
    }
}

// Nack request
fun nackRequest() {
    val requestBody = """
        {
            "ack_tokens": ["MTYyeJ7abUjl1pO", "MTYyeJ7abUjl1pP"]
        }
    """.trimIndent().toRequestBody(JSON)

    val request = Request.Builder()
        .url("https://api.sequinstream.com/api/http_pull_consumers/orders-pull-consumer/nack")
        .header("Authorization", "Bearer $API_TOKEN")
        .post(requestBody)
        .build()

    client.newCall(request).execute().use { response ->
        if (!response.isSuccessful) throw IOException("Unexpected code $response")
        println(response.body?.string())
    }
}
```
