### ISSUE TITLE
Does sequin respect timeout set in the web editor?

### ISSUE THREAD

**Issue by gerynugrh** [sequinstream/sequin#259]
We use sequin to run asynchronous workflow on our company, some of these workflow have a quite long running time (around 30s to 90s). We notice that although we've returned with status 200 successfully. The same record kept being replayed to us by sequin.

An example would be below:
```json
{
  "record": {
    "created_at": "2024-09-11T08:27:23Z",
    "file_name": "<file_name>",
    "file_path": "<file_path>",
    "id": "2luwPKhC0Rp2Ku13FcutL4mMYEU",
    "is_deleted": false,
    "mime_type": "image/jpeg",
    "parse_result": null,
    "state": "upload_complete",
    "tags": [
      ""
    ],
    "updated_at": "2024-09-11T08:27:26Z"
  },
  "metadata": {
    "consumer": {
      "id": "b6c2d92a-fcac-42e7-9191-508f4ff7349b",
      "name": "drive_files"
    },
    "table_schema": "public",
    "table_name": "drive_files",
    "commit_timestamp": "2024-09-11T08:26:52.425877Z"
  },
  "action": "update",
  "changes": {}
}
```

Sequin sent the records above on 11 September and kept replaying it once every few minutes until today.

I'm not too familiar with Elixir but I didn't see any mention of timeout set in the HTTP request, could there be a chance that due to timeout, sequin failed to receive our acknowledgement and keep replaying the message?

```ex
    req =
      [base_url: http_endpoint.base_url, url: http_endpoint_path || "", headers: headers, json: message_data]
      |> Keyword.merge(req_opts)
      |> Req.new()
```

**Comment by acco** [comment]
Hey @gerynugrh thanks for reporting the issue!

You were on the money. We needed to respect the consumer's `ack_wait_ms` in the HTTP push pipeline. That fix will be live in our cloud in <5min.

I noticed the request timeout/ack wait on your consumers is set pretty low (30s on most, 60s on one). This timeout should be conservatively high. If the timeout elapses, Sequin will consider the message failed, even if you eventually send a 200 response. (The request will have been killed on our end.)

If you have workflows that can take 60-90s, I recommend setting the request timeout/ack wait to at least 120s to give them some good buffer.

Make sense? Let me know if that fixes for you

**Comment by gerynugrh** [comment]
> Hey @gerynugrh thanks for reporting the issue!
> 
> You were on the money. We needed to respect the consumer's `ack_wait_ms` in the HTTP push pipeline. That fix will be live in our cloud in <5min.
> 
> I noticed the request timeout/ack wait on your consumers is set pretty low (30s on most, 60s on one). This timeout should be conservatively high. If the timeout elapses, Sequin will consider the message failed, even if you eventually send a 200 response. (The request will have been killed on our end.)
> 
> If you have workflows that can take 60-90s, I recommend setting the request timeout/ack wait to at least 120s to give them some good buffer.
> 
> Make sense? Let me know if that fixes for you

Yep I was doing some experiment on the timeout yesterday to figure out the issue, I'll change it back to a higher value
