### ISSUE TITLE
Set non-PKs as FIFO group ID

### ISSUE THREAD

**Issue by thisisgoldman** [sequinstream/sequin#348]
Provide strict ordering on any column.

**Comment by tazmaniax** [comment]
Is the idea to replicate AWS SQS FIFO queue group ID semantics? Will the non-PK group ID support multiple columns? Thanks

**Comment by acco** [comment]
@tazmaniax exactly! Right now, the group_id is always the PKs. Idea here is to let you select which columns (or set of columns) should serve as group_id. Then, the next record for a given group_id will only be delivered after the preceding one has been ack'd

We've done this on the backend, frontend should be rolled out today or tomorrow

**Comment by tazmaniax** [comment]
@acco is this something that I can test now? Thanks!

**Comment by RTLS** [comment]
@tazmaniax not yet Chris- I am beginning work on this now. Should complete it today.

**Comment by RTLS** [comment]
Hey @tazmaniax - this is live. You can set Group ID for new consumers that you create. Please let us know if this works as expected for you :D

**Comment by RTLS** [comment]
#433
