### ISSUE TITLE
Support large batch operations

### ISSUE THREAD

**Issue by acco** [sequinstream/sequin#465]
Right now, we collate all of a commit's rows in memory, then flush to Postgres on commit. As we anticipated, this does not work for very large commits that touch many, many rows.<br><br>We should flush to Postgres mid-commit, after our buffer has reached a certain size.

The simplest solution is to just flush, nothing extra. The downside is if we restart mid-way through, we'll replay messages, and possible re-write stuff that was already pulled from `consumer_records`.

To get idempotency, we could give each message in a commit an `idx` (as discussed in [SQN-3378](https://linear.app/sequin/issue/SQN-3378/separate-seq-from-commit-lsn)). Then, if we enter a large commit, we can can keep state about what we've written somewhere persistent like Redis. That way, if we're restarted and the commit begins to replay, we can skip messages until `idx`

**Comment by RTLS** [comment]
This was released in `v0.5.26`
