### ISSUE TITLE
Support active-passive deployments

### ISSUE THREAD

**Issue by acco** [sequinstream/sequin#581]
At the moment, Sequin does not support clustering. That means you should run Sequin as a **single-node** instance.

If you want to cluster Sequin (for high availability or greater throughput), please comment below or react to this issue.

**Comment by acco** [comment]
Hey @angrifel thanks for the comment! I'll discuss with team today and post back here. Good to hear your use case (HA).

**Comment by acco** [comment]
@angrifel We're thinking our initial approach here is going to be hot standby: so you can have >1 Elixir node running. One will have a mutex for running sink pipelines. If it crashes, within a few seconds, another running node will grab a mutex and take over.

Does that sound good for your requirements?

In the future, we'd let you distribute load across nodes

**Comment by angrifel** [comment]
@acco I think this is the right approach for a first iteration of HA in sequin. Let me know how can I help

**Comment by acco** [comment]
Hey @angrifel – this is ready! Want to give it a whirl and let us know if it works for you?

https://sequinstream.com/docs/reference/configuration#clustering-configuration

Outside of logs, you can confirm nodes are clustered by visiting `your-sequin-host.com/info`. `nodes` will list other nodes in the cluster

**Comment by angrifel** [comment]
@acco I'm just reading this. Is this available on `sequin/sequin:latest` ?

**Comment by acco** [comment]
@angrifel It is!
