### ISSUE TITLE
When I update any db row, if the row contains enumType, then sequin can't fetch the data... it shows simply null

### ISSUE THREAD

**Issue by samayun** [sequinstream/sequin#625]
# Enum Field Null Issue

## Database Table fields here 
![image](https://github.com/user-attachments/assets/357c0c7d-e2bb-47e7-9526-0c66ed7a5d66)

## Sequin fetched enum field as null
![image](https://github.com/user-attachments/assets/22bd1186-cc3a-4735-953b-988d2f21522f)

Issue  Video ( If needed): https://jam.dev/c/15c7ec17-4fb4-4b8e-afba-a0406230bb38

[![Watch the video](https://via.placeholder.com/800x450.png?text=Video+Preview)](https://jam.dev/c/15c7ec17-4fb4-4b8e-afba-a0406230bb38)

**Comment by acco** [comment]
Hey @samayun -- new release is ready for you! Let us know if the issue is not resolved.

**Comment by ronkkol** [comment]
Hey, I'm running the latest version of Sequin and Kafka sinks for tables with an enum column (with a custom type name) are failing completely. All messages get stuck on the ingestion step and logs show error:
`[error] Unknown message: %Sequin.Extensions.PostgresAdapter.Decoder.Messages.Type{id: 1123279, namespace: "public", name: "<CUSTOM_TYPE_NAME_HERE>"}`

Types are created as
`CREATE TYPE custom_type AS ENUM (
      'MANY',
      'DIFFERENT',
      'CASES',
      'HERE'
    );`

**Comment by acco** [comment]
Hey @ronkkol Looking at this now! The unknown message might be a red herring (we should suppress that log). Would you mind posting here or emailing me the full DDL for your source table? (anthony [at] sequinstream [dot] com)

Thanks

**Comment by acco** [comment]
Hey @ronkkol –

I suspect that the enum type is not the culprit. Not able to repro. Pushed a change that removes that log entry (released as `v0.6.32-alpha.1`). Any other log errors that you're seeing?

I assume the issue is that you make changes to the source table, but nothing flows through?

**Comment by ronkkol** [comment]
> Hey @ronkkol Looking at this now! The unknown message might be a red herring (we should suppress that log). Would you mind posting here or emailing me the full DDL for your source table? (anthony [at] sequinstream [dot] com)
> 
> Thanks

Here is the DDL for a table where the CDC data was not coming through:
```
-- Table Definition ----------------------------------------------

CREATE TABLE "MessageTopics" (
    id uuid PRIMARY KEY,
    "assignmentId" uuid,
    "createdById" uuid NOT NULL,
    "organizationId" uuid NOT NULL,
    "participantIds" uuid[],
    name text,
    status message_topic_status NOT NULL,
    "createdAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" timestamp with time zone,
    "externalId" text,
    "externalSource" text,
    "externalHash" text,
    "ownerId" uuid,
    "customerId" uuid
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX "MessageTopics_pkey" ON "MessageTopics"(id uuid_ops);
CREATE INDEX "MessageTopics_assignmentId_index" ON "MessageTopics"("assignmentId" uuid_ops) WHERE "assignmentId" IS NOT NULL;
CREATE INDEX "MessageTopics_createdAt_participantIds_index" ON "MessageTopics" USING GIN ("createdAt" timestamptz_ops,status enum_ops,"participantIds" array_ops);
CREATE UNIQUE INDEX messagetopics_externalid_unique_partial_index ON "MessageTopics"("externalId" text_ops,"externalSource" text_ops,"organizationId" uuid_ops) WHERE "externalId" IS NOT NULL;
```
And the offending type is: `CREATE TYPE message_topic_status AS ENUM (
      'OPEN',
      'IN_PROGRESS',
      'RESOLVED',
      'LOCKED'
    );`

And just for reference, data was going through fine for this table with no custom enum:
```
-- Table Definition ----------------------------------------------

CREATE TABLE "ProfileTypes" (
    id uuid PRIMARY KEY,
    "organizationId" uuid NOT NULL,
    color character varying(255),
    "detailsSchema" json,
    name character varying(255) NOT NULL,
    "permissionIds" uuid[] NOT NULL DEFAULT '{}'::uuid[],
    "createdAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deletedAt" timestamp with time zone,
    "externalId" character varying(255),
    "externalSource" character varying(255),
    "externalHash" character varying(255),
    "workContractRequired" boolean NOT NULL,
    "identityProviderIds" uuid[] NOT NULL,
    "termsId" uuid
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX "ProfileTypes_pkey" ON "ProfileTypes"(id uuid_ops);
CREATE INDEX profiletypes_organizationid_index ON "ProfileTypes"("organizationId" uuid_ops);
CREATE UNIQUE INDEX profiletypes_externalid_unique_partial_index ON "ProfileTypes"("externalId" text_ops,"externalSource" text_ops,"organizationId" uuid_ops) WHERE "externalId" IS NOT NULL;
```

**Comment by acco** [comment]
Hey @ronkkol - Thanks for providing those detailed table definitions, helped a lot. I am unable to reproduce the issue, changes appear to be flowing through fine for me.

Can you confirm that table is in your publication?

```sql
select * from pg_publication_tables 
where tablename = 'messagetopics';
```

If the table isn't showing up there, you'll need to add it to your publication with:

```sql
alter publication your_publication_name 
add table "MessageTopics";
```

If it's appearing there, we'll keep digging.

**Comment by ronkkol** [comment]
Yes, it's in the publication with column names `{id,assignmentId,createdById,organizationId,participantIds,name,status,createdAt,updatedAt,deletedAt,externalId,externalSource,externalHash,ownerId,customerId}`

**Comment by acco** [comment]
Hey @ronkkol – still having trouble reproducing. Wanna solve this synchronously? You can DM me in our Discord and we can do a screenshare there - that will probably be the fastest way for us to debug: https://discord.com/invite/BV8wFXvNtY
