### ISSUE TITLE
"Test connect" issue with Kafka in docker

### ISSUE THREAD

**Issue by acco** [sequinstream/sequin#641]
To reproduce, follow all the steps in the Kafka quickstart up until this point:

> **Configure "Kafka Configuration"**

Enter `host.docker.internal:9092` and click "test connection" - it won't work! Also no logs 🤔 <br><br>However:

* You can run test connect ok from a Sequin running *outside* docker (ie via `make dev`)
* You can still create the Kafka Sink — and it will work!

**Comment by RTLS** [comment]
[https://github.com/sequinstream/sequin/pull/653](https://github.com/sequinstream/sequin/pull/653)
