### ISSUE TITLE
Make Kafka's message `key` first-class

### ISSUE THREAD

**Issue by acco** [sequinstream/sequin#646]
Like [SQN-3414](https://linear.app/sequin/issue/SQN-3414/make-messagegroupid-first-class-for-sqs), we want to hoist up the concept of message key / blend with our concept of grouping. So that messages with the same group are routed to same partition.

**Comment by RTLS** [comment]
One path forward is to extend `group_id` from `ConsumerRecrod` to `ConsumerEvent` - in this case, we can then simply use the `group_id` as the `message_key`.<br><br>Alternatively, we can pass in the full `PostgresDatabaseTable` and `SequenceFilter` then dynamically generate the `message_key` from the `sequence_filter.group_column_attnums` and the values in the record or event data.<br><br>This latter path requires fewer changes and also allows the message key to be changed dynamically, ie. without migrating values in the consumer records or consumer events tables.
